### ISSUE TITLE
Imagex textbox paikka imagen kanssa fixedobjectine ei toimi

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#1061]
In GitLab by @Smibu on Feb 26, 2018, 17:38

Kun ImageX-pluginissa laittaa kiinteän kuvan ja sille textbox:in, niin sen paikka ei toimi.
Tekstiboksin paikka on samassa suhteessa imageen kuin imagen paikka on suhteessa
piirtoalueen paikkaan, eikä textboxproperties:lla oleva position vaikuta mitenkään.
Jos nuo olisi raahattavia objekteja, niin silloin toimii. Esim. alemman kuvan teksti on 360
pikseliä imagesta oikealle.

```
fixedobjects:
  -
    type: "img"
    position: [10, 20]
    id: "pilvi1"
    imgproperties:
      src: "http://users.jyu.fi/~arjuvi/opetus/itkp104/general/cloud.png"
      textbox: true
    textboxproperties:
      cornerradius: 5
      borderColor: "transparent"
      textColor: "black"
      position: [323, 82]
      text: Verkko 1
  -
    type: "img"
    id: "Router 1"
    position: [360, 20]
    imgproperties:
      src: "http://users.jyu.fi/~arjuvi/opetus/itkp104/general/router.jpg"
    textboxproperties:
      position: [0, 0]
      text: Reititin 1
```
