### ISSUE TITLE
csPluginiin sanapohjainen arvostelu

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#1263]
In GitLab by @vesal on Nov 18, 2018, 09:41

Arvosteluun lisävaihtoehto:

```
-pointsRule: 
  text_based:
    min_points: 0
    max_points: 4
    user_text:
      min_points: 0
      max_points: 4
      show_points: true
      rules:
      - regex: ".*mirri.*"
        comment: "Älä käytä mirri-sanaa!"
        points: -1
      - regex: ".*kissa.*"
        comment: "Hienoa, kissa on hyvä sana!"
        points: 3
      - regex: ".*koira.*"
        comment: "No miksei koirakin käy!"
        points: 2
    output:
      ... kuten edellä ...
```
