### ISSUE TITLE
qst uusi muoto ei tunne kaikkia vanhoja kysymyksiä

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#1269]
In GitLab by @vesal on Nov 24, 2018, 13:52

Esim:

````
``` {#Likert dquestion="Likert" plugin="qst"}
json:
  answerFieldType: radio
  headers: ['1', '2', '3', '4', '5']
  matrixType: radiobutton-horizontal
  questionText: Likert
  questionType: matrix
  rows:
  - "Onko hyvä"
  - "Onko lämmin"
  - {}
  title: Likert
```
````

Joskus piti olla tuo tyhjä rivi lopussa jonkin takia mitä en enää muista. Mutta on tuollaisia
kysymyksiä joissa tuo on ja ne eivät silloin näy.
