### ISSUE TITLE
mcq- ja mmcq-plugineiden laiska esitysmuoto on tyhjä, jos header ja stem on tyhjä

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#1416]
In GitLab by @Smibu on Jun 12, 2019, 10:15

Esim.

````
``` {#t plugin="mcq"}
headerText: ' ' 
stem: ' ' 
choices: 
  - 
    correct: false 
    text: 'a' 
    reason: '' 
  - 
    correct: true 
    text: 'b' 
    reason: '' 
  - 
    correct: false 
    text: 'c' 
    reason: '' 
```
````

ei näy laiskana lainkaan ja sitä ei siksi voi aktivoida.
