### ISSUE TITLE
Inline plugin ison pluginin syntaksilla

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#1496]
In GitLab by @vesal on Aug 18, 2019, 12:37

Voiskos kuvitella että nyt kun inlineplugin saa kirjoittaa
usealle riville `{# #}` ansiosta, niin sen sisältö saisi halutessaan
olla myös YAMLia.   Tarvitseeko koodia muuttaa paljon jos jollakin tavalla saisi
sanottua että tämä on YAMLia ja sitten  esim

````
#- {defaultplugin="csPlugin"}
{#GLO_T2
type: graphjs
width: 300    
data: 
    labels: [1,2,3,4,5,6,7,8,9,10,11]  
    data:   [0,4,0,0,0,0,9,0,0, 0, 0]
    title:  "kissat"
    label: 'Kpl'
    xlabel: 'Pistemäärä'
    ylabel: 'Lukumäärä'
    trend: true
    dataopt: 
        lineTension: 0.4 
#}
````

tuo # rivien välinen osa (eli käytännössä pluginin sisältö) kiertäisi YAML-tulkin läpi.

Olisi helpompi muuttaa tarvittaessa isoja pluginea inline-plugineiksi esim jos haluaksi
monta graafia samalle riville.
