### ISSUE TITLE
Firefoxilla timtablessa on vaakavierityspalkki

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#1654]
In GitLab by @Smibu on Feb 5, 2020, 17:06

Firefoxilla leveitä timtableja joutuu rullaamaan erikseen vaakasuunnassa.

Tämän kanssa olen paininut kohtalaisen kauan, mutten ole saanut taulukkoa näkymään halutulla tavalla.

Löysin [tämän vastauksen](https://stackoverflow.com/a/6433475) joka varmaankin liittyy asiaan. Sen mukaan kombinaatio

```css
.jotakin {
  overflow-x: visible;
  overflow-y: auto;
}
```

ei ole mahdollinen, vaan `visible` tulkitaan `auto`ksi. Chrome ilmeisesti toimii sattumalta.
