### ISSUE TITLE
timtablen solun värjäys ei toimi kaikissa soluissa

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#1700]
In GitLab by @Smibu on Mar 3, 2020, 15:31

Esim. [demodokumentin](https://tim.jyu.fi/view/kurssit/tie/ohj2/2020k/demot/Demo9) pöytätestitehtävässä ei toimi solun värjäys sarakkeessa "staattiset" riviltä "25 vari++;" lähtien. Ensimmäinen sarake (missä koodirivit on listattu) toimii.

Sain tehtyä vielä [Pienemmän](https://tim.jyu.fi/view/users/vesal/koe/timtable/changecolor).
Tuo alempi taulukko on tehtävä ja sen viimeisen sarakkeen värejä ei voi muuttaa.

Tuosta:

````
``` {plugin="timTable"}
task: true
table:
  countCol: 5
  countRow: 3
  rows:
  - row:
    - cell: ''
    - cell: ''
      cell: ''
  - row:
    - cell: ''
      cell: ''
    - cell: ''
```
````

voi muuttaa kahta ekaa riviä ja saraketta.  Tuosta ei voi muuttaa mitään:

````
``` {plugin="timTable"}
task: true
table:
  countCol: 5
  countRow: 3
```
````

Vastaavasti tuossa voi värjätä ekan rivin 2 solua ja 2 rivin 3 solua

````
``` {plugin="timTable"}
task: true
table:
  countCol: 5
  countRow: 3
  rows:
  - row:
    - cell: ''
    - cell: ''
  - row:
    - cell: ''
    - cell: ''
    - cell: ''
```
````

Vika lienee siinä, että soluja, joille ei ole mitään alku"sisältöä", ei voi värjätä.
