### ISSUE TITLE
TIMiin ajanvaraus niin, että näyttää muiden tekemien ruksien määrät ja on ylärajat

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#1791]
In GitLab by @vesal on Apr 25, 2020, 10:42

Vaikka ajat jaettaisiin niin, että ruksivat mahdolliset ajat
ja niistä lasketaan parhaiten sopiva jako, voisi silti
näyttää kunkin ruksin kohdalla moniko on saman ajan ruksinut.
Ja ohjeessa kehotettaisiin laittamaan rukseja myös niihin kohtiin,
joissa on vähän rukseja, jotta ajat saadaan riittämään paremmin.

Eli kyllä tuota silti voisi lähteä miettimään sellaisen komponentin
kautta, johon ruksitaan aikoja ja liian montaa ei saa ruksia.
Tässä tapauksessa vaan rajoiksi laitettaisiin riittävän isot.

Yleistä ajanvarausta varten:

* [x]  ruutua ei näytetä jos määrä ylittynyt (jos määrä >0 näytetään määrä tai vapaat kuitenkin, attribuutti)
* [ ]  jos tallennushetkellä jokin ruutu on jo ylittänyt määrän, ei siihen ruutuun
       tallenneta

Ohj-kursseja varten lisäksi:

* [x]  sähköpostia mikäli ruksi lähtee/tulee ruutuun tietyn ajanhetken jälkeen (attribuuttina sp)
* [x]  attribuutilla voi rajoittaa milloin saa "vastata" (taitaa jo ollakin), mutta voisi olla
       "selväkielisempi", vrt Korpin ajanvaraus

Kalenteriasioita EI tehdä vk20 projektissa ja se voi vaatia että koko komponentti uusiksi:

* [x]  automaattinen muodostaminen päivät vaakaan tai pystyyn kun annetaan varausajan pituus (vrt Korppi)
* [x]  integrointi kalenteriin niin että omat ruksit näkyvät kalenterissa
* [x]  integrointi kalenteriin niin, että jos kalenterista poistaa tapahtuma, ruksi lähtee pois
* [ ]  integrointi kalenteriin niin, että rukseja tehdessä näkyy omat menot

### Käyttötapaus: Luennot + pääteohjaukset

```
timezone: Europe/Helsinki  # oletus
weeks: [35-38, 40]
weekdays:  # oletus
 - mon
 - tue
 - wed
 - thu
 - fri
weekevents:
 luento:
  - [Luento 1, 'mon 10:15-12:00']
  - [Luento 2, 'tue 12:15-14:00', {weeks: [36, 41]}]  # oletusviikoista poikkeavat
 paate:
  - [Pääte 1, 'wed 10:15-12:00', {max: 15}]
  - [Pääte 2, 'thu 12:15-14:00']
events:  # tähän voi lisätä epäsäännöllisiä tapahtumia
 - [Muu tapahtuma, '6.11.2020 14:00-15:00']
eventgroups:
 luento:
  suggestAllInEventGroup: true  # jos yhdenkin luennon ruksii, niin ehdotetaanko, että ruksitaan kaikki
 paate:
  suggestForEachWeek: true  # ehdotetaanko jokaisen viikon osalta saman tapahtuman ruksimista
  max: 20  # oletusmaksimiosallistujamäärä jokaiseen tämän ryhmän tapahtumaan
  maxPerPerson: 1  # yksi henkilö voi osallistua korkeintaan näin moneen tämän ryhmän tapahtumaan per viikko
```

### Käyttötapaus: Harjoitustöiden ohjausaikojen asettaminen ja varaaminen

```
weeks: [35-38, 40]
weekevents:
 ohjaus:
  - [Ohjaus, 'mon 8:00-18:00', {splitToMulti: 20mins}]
  - [Ohjaus, 'tue 8:00-18:00', {splitToMulti: 20mins}]
filterEvents:
 right: view
 deadline: 6h  # ajat varattava viimeistään 6h etukäteen
 allowIfHasParticipant: ohj1  # näytetään view-oikeudellisille vain ne ajat, joissa on ainakin 1 ohj1-ryhmään kuuluva
eventgroups:
 ohjaus:
  max: 2  # ohjaaja + opiskelija
```

Ratkaisemattomat ongelmat:

* Jos harjoitustyö halutaan tehdään ryhmässä, miten se ilmaistaan? Tuntuisi, että answer-taulu taipuu tähän huonosti.
