### ISSUE TITLE
Säädettävä minimaalinen kirjautuminen

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#1793]
Liittyy #1776 listaan

Heitän tänne muutaman toteutusvaihtoehdon pohdintaan
* ~~Lisätään yleinen `RESTRICT_LOGIN` config-optio Flaskin konfiguraatioon (eli `defaultconfig.py` ym)~~ tässä tapauksessa riittää vain sivukohtainen käyttöliittymärajoitus
    * Sammuttaa kaikki kirjautumisvaihtoehdot paitsi TIMin oma
    * Estää samalla rekisteröitymisen verkkosivun kautta (?)
    * Plussana on, että toimii globaalisti: backendissa konfiguraatioon pääsee kiinni kaikkialta, frontendiin lähtetetään muiden globaalien kanssa
    * Helppoa toteuttaa: [alustava proof-of-concept](https://gitlab.com/dezhidki/tim/-/commit/f07789eb4ec42473d9d739f57846ddc02132012b)
* Lisätään jokin yleinen asetus "sivulle"
    * Nyt indexilla ei ole (?) tällaista sivukohtaista konfiguraatiota, eli pitää joko ohjata uudelle sivulle (onko tämä ajatus) tai toteuttaa sille konfiguraatiomahdollisuus
    * Toisaalta plussana se, että voi säätää, vaikka TIM on jo käynnissä
    * Toimintaperiaate: dokumentin asetuksiin voi määrittää `login`-objekti, jolla voi piilottaa kirjautumisvaihtoehtoja:
      ```yaml
      login:
          hideHaka: true
          hideSignup: true
          hidePasswordRecovery: true
          hideEmailLogin: true
      ```
    * [esimerkin toiminnallisuuden diff](https://gitlab.com/dezhidki/tim/-/commit/86c6d30c771f3e2b0b478d6db443e6bbcf8d5cdd)
    * Pitäisikö laittaa ryhmittää ne `hide`-objektin taakse ajatellen tulevaisuutta? Eli olisi mallia
      ```yaml
      login:
          hide:
              haka: true
              signup: true
              passwordRecovery: true
              emailLogin: true
      ```
