### ISSUE TITLE
showVideo-plugin luo invalidin linkin iframelle, jos alkuperäisessä linkissä on URL-parametreja

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2290]
`showVideo`-plugin ei osaa käsitellä iframe-tilassa linkkejä, joissa on jo valmiiksi URL-parametreja

## Toistaminen

1. Tee uusi dokumentti
2. Lisää uusi lohko ja laita sen sisään showVideo-plugin seuraavalla markupilla:
    ```yaml
    footer: "Video 1: Jotain komentorivistä"
    iframe: true
    width: 800
    height: 600
    file: https://m3.jyu.fi/jyumv/embed?uid=627ec66fa5d74a83b6f5b1862fe93677
    ```
3. Tallenna lohko ja yritä avata video

## Virhetila

Video ei tule näkyville. Kun katsoo iframen markupia devtoolsin kauttaa, sen `src`-attribuuttina on `https://m3.jyu.fi/jyumv/embed?uid=627ec66fa5d74a83b6f5b1862fe93677?` (huomaa kaksi kysymysmerkkiä)

## Muuta

Väliaikaisesti tämä korjaantuu sillä, että laittaa `file`:n loppuun `&`-merkki, jolloin näin saatu `&?` tulkitaan url-parametriksi. Tämä kuitenkaan ei ole yhteensopiva videon aloitusajan säädön kanssa.
