### ISSUE TITLE
QST:n tulostus epäonnistuu laajennetulla header-objektilla

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2375]
Jos on esimerkiksi

``````
``` {#teht dquestion="true" plugin="qst"}
answerFieldType: checkbox
expl: {}
headers:
- '1'
- '2'
- id: 1
  text: '3'
  type: header
- id: 1
  text: '4'
  type: header
- '5'
- '6'
matrixType: checkbox
questionText: Merkitse tekemäsi tehtävät
questionTitle: teht
button: Tallenna
questionType: matrix
rows:
- ''
```
`````` 

LaTeX-tulostuksen aikana tulee 

```

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/service/timApp/plugin/qst/qst.py", line 369, in qst_multimd
    multi.append(qst_get_md(jso))
  File "/service/timApp/plugin/qst/qst.py", line 708, in qst_get_md
    theader += sep + h
TypeError: can only concatenate str (not "dict") to str
```

Tulostus onnistuu, mutta QST:n kohdalla näkyy virheviesti.
