### ISSUE TITLE
Mahdollisuus hakea vastaushistoria JSRunneriin

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2417]
Mahdollinen syntaksi

```yaml
fields:
  - field1
field_history:
  field1: # Muuten samat parametrit kuin allAnswers -polussa
    age: all
    valid: all
```

Vastaavasti JSRunneriin `getInt`, `getString` lisäparametri, jolla voi kysyä tiettyä vastausta. Ehkä samalla voisi olla apumetodeja, jolla haetaan kaikki vastaukset listana (`getInts`, `getStrings` yms).
