### ISSUE TITLE
UserSelect lukemaan kestoja ja aikoja fieldeistä

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2448]
Tällä hetkellä UserSelect-pluginin "dynaaminen" konfigurointi onnistuu makroilla. Esimerkiksi lisäaikaa antaessa on käytetty alasvetoja ja urlmakroja. Mutta

* tämä ei ole kätevää, urlmakrot "unohtuvat" URLin vaihdon yhteydessä
* joskus on tarve valita UserSelectin kautta annettavat arvot henkilökohtaisesti, esimerkiksi duration-oikeuden keston hakeminen jostain fieldista

Tätä varten UserSelectiin pitäisi pystyä määriittämään JSRunnerin tapaisesti fieldeja ja pystyä käyttämään niitä "muuttujina" markupissa.

Esimerkiksi voisi olla

```yaml
fields:   # Sanotaan, että UserSelect tarvitsee seuraavat fieldit
  - kesto
actions:
  addPermission:
    doc_path: some/doc
    type: view
    time:
      duration: "$kesto" # Tai joku vastaava syntaksi, joka ei ole itsessään makro
```
