### ISSUE TITLE
csPlugin: `buttons`-toimintoon Markdown-tuki

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2528]
- [x] MarkDown mdButtons
- [ ] items-attribuutti mdButtons
- [ ] placeholder-attribuutti editorTempaltes
- [ ] editorTempates myös editoriin (jos haluaa toiminnot editorin yläpuolelle)
      tai molempiin

Esimerkiksi voitaisiin sallia kolme syntaksia:

1. Merkkijono

```yml
buttons:
  - "md: *Teksti*"
  - "md: **Teksti**"
```

2. Lista:

```yml
buttons:
  - [ "md: **Teksti**", "**Teksti**", "Lihavoitu" ]
  - [ "md: *Teksti*", "*Teksti*", "Kursiivi" ]
```

3. Pitkä:

```yml
buttons:
  - template: "**Teksti**"
    buttonText: "md: **Teksti**"
    title: "Lihavoitu"
  - template: "\\1 + \\2"
    buttonText: "md: $a + b$"
    placeholders:
      - default: a
        prompt: "Mitä summataan?"
        pattern: "[A-z0-9]+"
        error: "Pitää olla kirjain tai numero"
      - default: b
        prompt: "Mihin summataan?"
        pattern: "[A-z0-9]+"
        error: "Pitää olla kirjain tai numero"
```

Ajatuksena on se, että YAML-syntaksin kanssa `md:`-arvot saadaan jo prosessoitua palvelimen puolella etukäteen.

Pohdittavaa:

1. Tarvitaanko nyt nämä kaikki esitysmuodot? Nämä pitäisi onnistua määrittämään käyttämällä Pythonissa tyyppiä `list[str] | list[tuple[str, str, str]] | list[ButtonOptions]`, missä `ButtonOptions` on oma dataclass. Toisaalta kolme eri tyyliä joutuisi ensin parsimaan jotenkin palvelimen tai selaimen puolella erikseen. Sinänsä riittää, että edes tuo (2) toimisi.

2. `buttons` on jo käytössä, joten pitänee keksiä uusi nimi parametrille.
