### ISSUE TITLE
JSRunner: Lomakkeiden generointi ja wizardit

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2558]
Mahdolliset käyttötarkoitukset:

* Luoda tentille sisääkirjaussivu, saliryhmät, valvojaryhmät sekä asettaa kaikki oikeudet kuntoon kerralla
* Lisätään uusi keskusteluketju keskusteludokumenttiin
* Luodaan uusi tutkielman pohja henkilölle henkilön nimen, tutkielman nimen, ohjaajan ja kurssin perusteella. Samalla asetetaan sopivat oikdet tutkielmadokumentteihin sekä luodaan ohjaajalle mahdolliset valmiit velppipohjat
* Luodaan uusi viestilista
* Luodaan uusi preamble
* Luodaan kurssisivu pohjasta

Näitä tilanteita yhdistää jonkinlainen TIM-operaatioiden suorittaminen käyttäjän syötteen perusteella. Edellä mainitut tilanteet voitaisiin ratkaista jonkinlaisella "wizard"-lomakkeella, jolla käyttäjältä kysytään tietoa ja joka suorittaa tietojen perusteella jonkinlaisia käyttäjäoperaatioita TIMiin.

### Ajatuksia toteutuksista

JSRunneriin voitaisiin määrittää jonkinlainen syötteitä määrittävä attribuutti:

```yaml
args:
  - type: doc
    name: tentti_doc
    label: Tenttidokumentti
  - type: string
    name: tentti_group
    label: Tenttiin osallistuvien opiskelijoiden ryhmä
  - type: list
    name: salit
    label: Salit
    description: Listaa salit, jotka käytetään kokeessa. Jätä tyhjäksi, jos saliryhmiä ei ole
  - type: checkbox
    name: onko_eta
    Label: Kokeessa on etäryhmä
```

Inspiraationa voisi käyttää GitHubin korttien lomakejärjestelmää ([GitHubin ohje ja esimerkki](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms))

JSRunneriin puolestaan tarvittaan uutta logiikka dokumenttien manipulointiin. Koska tällaiset skriptit voivat kasvaa hyvin monimutkaiseksi, suoraan dokumenttien muokkaamisen sijaan voitaisiin käyttää *operaatioita*. Eli esimerkiksi JSRunnerissa

```js
tim.createFolder("/kurssit/ITKP101");
tim.copy("/kurssit/mallikurssi", "/kurssit/ITKP101");
tim.createGroup("group1");
tim.setPermission("/kurssit/ITKP101", [{
  type: "view",
  to: "group1"
}]);
```

määrittelisi neljä operaatiota:

* Luo kansio `/kurssit/ITKP101`
* Kopioi kansion `/kurssit/mallikurssi` sisältö kansioon `/kurssit/ITKP101`
* Luo ryhmä "group1"
* Anna ryhmälle "group1" view-oikeus kansioon `/kurssit/ITKP101`

JSRunner palauttaa TIMille listan toteutettavista operaatioista. TIM tarkistaa operaatioiden oikeudet ja suorittaa ne. Tällä tavoin varmistetaan, että JSRunnerin kaatuessa ei jäädä "välitilaan", jossa osa operaatioista on jo suoritettu.
