### ISSUE TITLE
csPlugin count-attribuutti

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2605]
In GitLab by @vesal on May 18, 2022, 11:52

csPlugin count-attribuuttin toimimaan niin, että toimisi:

```
count:
  preventSave: true
  tooManyWord: "För många"
  tooFewWord: "För få"
  #lines: {show: true, min: 2, max: 4, text: "rader"}
  words: {show: true, max: 100, text: "ord"}
  # chars: {show: true, min: 10, max: 40, text: "bokstäver"}
```

jolloin `text` näkyy sekä laskurin otsikkona ja virheilmoituksissa tekstin perässä.  Jos
Virheilmoituksissa on "paikkamerkki", niin silloin text tulostuu siihen.

Jos yksittäisten laskureiden attribuuttiin laitetaan ko virheilmoitukset, niin ne voittavat
nuo yhteiset.  `show`-attribuutin arvo oletuksena false.  Myös `preventSave` voisi olla mahdollista
laittaa laskurikohtaisesti.

Pitää tarkastaa kuinka paljon tuota on käytetty ettei riko samalla olemassa olevia.  Tosin tuolla
määrittelyllä ei pitäisi rikkoutua.  

Jatkona vielä että onko erikseen `warningText: Varoitus`
ja `warningMin`ja `warningMax`, jossa tulee varoitus jos meinataan lähestyä rajoja.  Tälle ei tällä
hetkellä käyttötapausta.
