### ISSUE TITLE
Login-kohtien piilotus dokumenttikohtaisesti - [merged]

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2689]
_Merges master -> master_

Dokumentin asetuksiin voidaan määrittää `login`-objekti:

```yaml
login:
    hideHaka: true              # piilottaa Haka-kirjautumisen
    hideSignup: true            # piilottaa TIMin rekisteröitymisen
    hidePasswordRecovery: true  # piilottaa "unohdin salasanani"-painikkeen ja sen UI:n
    hideEmailLogin: true        # piilottaa TIMin oman sisäänkirjautumisen
```

Kaikki kohdat ovat valinnaiset (oletusarvo on `false`). Asetuksien käyttäminen pätee vain tietylle dokumentille eikä se itse estä kirjautumasta sisään Hakan API:lla.
