### ISSUE TITLE
TimeLeftComponent: mahdollisuus synkronoida kello - [merged]

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2745]
_Merges fix-timeleft-precision -> master_

Muuttaa countdownin ja timeleftin toimintaa seuraavasti:

* Countdownin arvoa voidaan synkronoida palvelimen kanssa säännöllisin väliajoin
   * Aika ja sen satunnainen hajonta ovat säädettävissä dokumenttiasetuksina
* Aika synkronoidaan lisäksi automaattisesti ainakin kerran, kun sirrytään "pienen aikarajan" tilaan (eli kun kello siirtyy välkkyvään tilaan)
* Ajan synkronoinnissa otetaan huomioon itse synkronointiin (palvelinkutsu + laskut) kulunut aika
   * Tällä hetkellä siitä ei arvioida erikseen RTT-arvoa, mutta se on tarvittaessa mahdollista lisätä
* Mahdollisuus säätää countdownin päivitystiheys dokumenttiasetuksena
* Muutettu countdownin templatea, jotta se on ystävällisempi Angular 9:n Ivy-moottorin muutoksien havainnoinnille

Dokumenttiasetuksiin on lisätty seuraavat arvot (ja niiden oletusarvot):
```yaml
answer_submit_time_tolerance: 1000 # Validien vastauksien vastaanottotoleranssi millisekunteina. Kun aika loppuu, tämän ajan (ja grace_periodin) sisällä lähetetyt vastaukset merkataan valideiksi.
time_left:
  sync_interval: 600          # Kuinka kauan odotetaan ennen seuraavaa synkronointia
  sync_interval_deviation: 0.2 # Satunnainen hajonta synkronoinnin odotusajalle. Esim. 0.2 = seuraava synkronoinnin aika vaihtelee satunnaisesti 20% sen arvosta.
  low_time_threshold: 60       # Aikaraja, jonka jälkeen kello menee "pienen aikarajan" tilaan
  low_time_glow_period: 45      # Kuinka kauan odotetaan pienen aikarajan tilassa ennen kuin kello välkkyy seuraavan kerran
  low_time_glow_duration: 15    # Kuinka kauan kello välkkyy punaisella pienen aikarajan tilassa
  low_time_sync_interval: 30    # Kuinka kauan odotetaan ennen seuraavaa synkronointia pienen aikarajan tilassa
  low_time_sync_deviation: 0.15 # Satunnainen hajonta synkronoinnin odotusajalle pienen aikarajan tilassa
``` 

Kaikki yllä olevien dokumenttiasetuksien ajat ovat sekunteina ellei toisin mainittu.

Testattava versio löytyy timdevsista
https://timdevs01-2.it.jyu.fi/view/users/test-user-3/timetest

Tässä ovat käytössä yllä mainitut oletusarvot. `testuser1`-käyttäjälle on annettu lukuoikeus 13.6. klo 00.00 asti.  
Mikäli haluaa dokumenttiasetuksia muuttaa, tulee kirjautua `testuser3`-tunnuksella.
