### ISSUE TITLE
DataViewComponent - [merged]

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2782]
_Merges feature-timtable-dataview -> master_

Lisää DOM-pohjaisen taulukkonäkymän TimTableen. Taulukkonäkymä soveltuu suuren datamäärän näyttämiseen ja käsittelyyn eikä siten toteuta kaikkia TimTablen ominaisuuksia. Uusi taulukkonäkymä voi kytkeä päälle lisäämällä TimTablen argumentiksi

```yaml
dataView:
  virtual: {}
```

Uusi taulukkonäkymä toimii kahdessa tilassa: DOM-taulukkona, jossa kaikki rivit laitetaan suoraan DOMiin ilman Angularin vaikutusta; sekä virutaalisena taulukkona, jossa edellisen lisäksi vain näkyvät rivit laitetaan DOMiin. Tilan voi vaihtaa asetuksella:

```yaml
dataView:
  virtual: # Jos tämä määritellään, virtuaalinen skrollaus kytketään päälle automaattisesti
    enabled: true  # kytkee virtuaalisen tilan päälle tai pois; oletuksena true
    verticalOverflow: 1 # Pystysuoran ikkunan suuruus. Tällöin DOMiin laitetaan `2 * verticalOverflow * nakyvat_rivit` verran rivejä enemmän, mikä vähentää päivityksien määrän skrollauksen aikana
    horizontalOverflow: 1 # Vaakasuoran ikkunan suuruus
  tableWidth: max-content # Taulun leveys. Tämä on erillinen asetus TimTablesta, sillä tämä käyttäytyy eri tavalla kuin TimTablessa (esim. fit-content saa taulun mahtumaan dokumentin leveyteen). Oletusasetus `max-content` (eli näytetään kaikki sarakkeet).
  rowHeight: 30 # Rivikorkeus px-arvona. DOM-taulussa tämä on "ideaalinen" minimiarvo, virtuaalisessa taulussa tämä on pakotettu korkeus. Oletus 30
  columnWidths: # Sarakkeiden leveydet. Jos ei määritetty, lasketaan automaattisesti. Suositellaan virtuaaliselle taululle, sillä automaattinen määrittely hidastaa latausta.
    '0': 50
    '1': 100
    '2': 200
    # jne
  fixedColumns: 0 # Kuinka monta ensimmäistä saraketta kiinnitetään. Kiinnitetyt sarakkeet eivät skrollaannu vaakasuuntaisesti silloin, kun tableWidth **ei ole** max-content.
```

Testisivuksi on tehty 3000 käyttäjän usergroup:

https://timdevs01-2.it.jyu.fi/view/groups/mockdata1

TODO:

* [x] Alustavat testit ja yleinen toteutus eristetyssä ympäristössä (https://deni.sh/angular_tabletest/ ja https://github.com/dezhidki/angular_tabletest)
* [x] DOM-taulukon perusintegrointi TIMiin
    * [x] TimTableen attribuutti, jolla lähtee päälle
    * [x] Tyylien säätäminen, että toimii
    * [x] Rivien filtteröinti
    * [x] Rivien valinta (eli checkbox)
    * [x] Rivien järjestäminen
    * [x] Solujen editointi (melkein valmis; pitää vaan korjata bugi, jossa data ei päivity taulukkoon)
* [x] Virtuaalisen skrollauksen kytkeminen päälle
    * [x] TimTableen attribuutti
    * [x] Sarakkeiden leveyden automaattinen määrittely, jos ei annettu staattista arvoa
    * [x] Testaa, että DOM-taulukon ominaisuudet toimivat edelleen (filtteröinti, valinta, järjestäminen)
* [x] Testausta, testausta
   * [x] Chrome, Windows & Linux (DOM taulun perustyyli toimii)
      * [x] Data-taulun reunukset häviävät skrollatessa virtuaalisessa taulussa
   * [x] Firefox, Windows & Linux (DOM taulun perustyyli toimii)
   * [x] Safari, macOS & iOS
      * [x] Jos filtteröi alkioita, taulukon koko ei muuttunut pienemmäksi
      * [x] iPadilla skrollaus välkkyy liikaa; eli piilotusefekti pois iPadilla
   * [x] ~~Esi-Chromium Edge, Windows (pitääkö edes testata)~~ sama kuin IE, ei testata
   * [x] Chrome & Firefox, Android
      * [x] Jos skrollaa ei-virtuaalista akselia pitkin, alkiot muuttuivat näkymättömiksi
* [x] Vanhojen testien korjaaminen, jotka menivät rikki edellisten säätöjen takia
* [x] Korjaamisia ja lisäyksiä
    * [x] Jos filtteröi ja rullaa loppuun, kaikki häviää (varmaankin viewport ei päivity filtteröinnin jälkeen)
    * [x] Virtuaalisessa skrollauksessa otsikkosarakkeen leveys ei synkronoidu datan kanssa alussa
    * [x] Mahdollisuus määrittää taulun leveys niin, että ei mene olemassa olevan `maxCols` kanssa ristiin
    * [x] Kenttien lisäyksen jälkeen otsikot edelleen sekaisin
    * [x] Preview-näkymässä näytetään vain pieni osa taulusta (nyt niin, että näytetään otsikot + rivien lkm)
    * [x] Optimoi koon uudelleenlaskenta, kun klikataan enter/tab
    * [x] Mahdollisuus lisätä data-sarakkeita ei-rullaavaan osaan (esim. https://timdevs02-5.it.jyu.fi/teacher/kurssit/tie/valintakokeet/tktyhteis/hakijat#runner2)
    * [x] Kun on `open: false`, menee rikki
    * [x] Toteuta skrollaus kenttään, kun se klikataan
    * [x] Reunukset saattoivat hävitä, jos skrollasi liikaa
    * [x] Rivikorkeus on kovakoodattu 30px. Lisää asetus, jolla voi asettaa rivien korkeus ja sarakkeiden leveys (tai että nämä arvot määritetään automaattisesti)
    * [x] Dialogi, jolla voi kopioida automaattisesti lasketut sarakeleveydet YAMLiin
