### ISSUE TITLE
Lisää CSS muuttujia SCSS-muuttujien tueksi - [merged]

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2804]
_Merges feature-vars-as-css-props -> master_

Vie SCSS-muuttujat CSS-ominaisuuksina. Tämä mahdollistaa muuttujien käytön käyttäjien omissa teemoissa sekä dokumenttikohtaisissa tyyleissä, esimerkiksi seuraavasti:

```css
body {
    background: linear-gradient(var(--bg-color), var(--gray));
}
```
Tässä `--bg-color` ja `--gray` määräytyvät tämänhetkisestä tyylistä.

Samalla tämä mahdollistaa tyylimuuttujien käyttöä Angular-komponenteissa ilman lisälogiikkaa aktiivisen tyylin tarkistukseen.

Tämä muutos ei ole täydellinen, vaan pohdin muutamaa asiaa, johon toivoisin kommentteja:

* Tällä hetkellä tämä muutos vain vie SCSS-muuttujat CSS-muuttujiksi, eli tyylien puolella käytetään edelleen SCSS-muuttujia. Tämä tarkoittaa, että käyttäjä **ei voi** vaihtaa tyyliä itse asettamalla
    ```css
    :root {
      --bg-color: red; /* Tämä sijoitus ei muuta taustan väriä, koska tyyleissä käytetään SCSS-muuttujia CSS-muuttujien sijaan */
    }
    ```
    Mietinkin: pitäisikö tämä sallia? Tämä vaatii suurempaa tyylien korjailua, sillä tässä tapauksessa pitäisi käydä kaikki SCSS-tiedostot läpi ja korvata SCSS-muuttujat CSS-muuttujilla. Samalla osan muuttujista ei voi näin viedä (esim. Bootstrap-muuttujat, sillä se on erillinen kirjasto).
* Tarvitseeko välttämättä viedä kaikki muuttujat CSSään? Esimerkiksi Bootstrapin muuttujista ei paljon hyötyä ole, ja suuri osa muuttujista vain copy-pastea toisen muuttujan arvot (esim. monet `$*-bg-color`-muuttujat ottavat arvon suoraan `$bg-color`-muuttujasta.
* En ole varma, pitäisikö vientikoodi muuttaa edelleen. Tein nyt `exportable`-funktion, joka vie funktion arvon CSSään. Toisaalta pelkään, että se saattaa olla liian pitkä kirjoittaa.
