### ISSUE TITLE
Oikeus ajaa tools.addToGroup avoimille ryhmille

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#3125]
JSRunnerin `tools.addToGroup` voi sallia suorittamaan avoimille ryhmille (#3106). Varmistusta varten riittää, että ryhmän hallintadokumenttiin listataan sallitut runnerit:

```yaml
groupSelfJoin:
  allowedRunners:
     - 123.testi
```

Tämä ratkaisu on väliaikainen kunnes ehditään tehdä järkevämpi jsrunnereiden oikeuksien hallinta.
