### ISSUE TITLE
TimTable: countRow-asetuksella lisättyjen rivien poistaminen taulukkoeditorista tyhjentää muita rivejä

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#3240]
### Esimerkki

1. Tee dokumenttiin taulukko:

        ````
        ``` {plugin="timTable"}
        table:
          countCol: 5
          countRow: 5
          rows:
          - row:
            - cell: '1'
            - '2'
            - '3'
            - '4'
            - '5'
          - row:
            - '6'
            - '7'
            - '8'
            - '9'
            - '10'
        ```
        ````
2. Avaa taulukon taulukkoeditori (lohkomenu -> Edit table)
3. Paina rivin kohdalla olevaa `-` -painiketta (rivin poisto) **kerran**
4. Virkistä sivu

### Mitä tapahtuu

* Kohdan 3 jälkeen taulukon tila ei virkistynyt
* Taulukossa on 5 riviä, mutta toinen rivi (6 7 8 9 10) hävisi

### Mitä pitäisi tapahtua

Tätä tilannetta ei varmaan ennen otettu huomioon perustauluissa, joten käyttäytymiselle on eri vaihtoehtoja:

* **Tehtään samoin kuin tehtävä-taulukoissa** eli piilotetaan `-`-painike jos poiston jälkeen rivejä olisi vähemmän kuin `countRow`. Tämä on helpoin ja tehtävissä järkevä (koska tehtävät ei voi muttaa markupia), mutta se varmaan hankaloittaa perustaulukoiden käsittelyä.
* Vähennetään `countRow` jos poistettava rivi ei ole oikea (eli puuttuu merkintä `rows`-listassa). Tämä tosin ehkä poistaa `countRow`in hyödyn, eli että taulukkoon voi antaa minimikoko.

Varmaan pikainen korjaus (jotta vältytään ihmettelyä siitä, miksi taulukko menee "rikki" tai miksi poisto tapahtuu väärästä kohdasta) olisi tosiaankin yhdenmukaistaa poistopainikkeen näyttämistä samaan tilaan kuin tehtävissä. Pidemmän päälle voi toki sallia `countRow`in muuttamista myös suoraan editorin toiminnalla.
