### ISSUE TITLE
Kutsuttavien makrojen määritteleminen johdantoasiakirjaan

### ISSUE THREAD

**Issue by Tuplanolla** [TIM-JYU/TIM#3454]
Haluaisin määritellä johdantoasiakirjan `macros`-kenttään
seuraavanlaisen funktion tapaan kutsuttavan makron,
joka poimii käännetyille kentille käännökset, ja
palauttaa muiden kenttien arvot sellaisenaan.

``` jinja
{% macro localize(value) %}
{% set iso_639_1 = doclang[0 : 2] if doclang else language %}
{% if value[iso_639_1] is defined -%}
%% value[iso_639_1] %%
{%- else -%}
%% value %%
{%- endif %}
{% endmacro %}
```

Jos asetuksissani olisi esimerkiksi seuraavat tapahtumat...

``` yaml
macros:
  events:
  - title:
      fi: "Rekursio ja vipellys"
      en: "Recursion and Iteration"
  - title: "Fin"
```

...niin voisin tarjoilla niiden oikeat käännökset seuraavalla makrolla.

``` jinja
{% for event in events %}
%% localize(event.title) %%
{% endfor %}
```

Miten tällaisen makron voisi määritellä?
