### ISSUE TITLE
YAML käyttäytyy omituisesti

### ISSUE THREAD

**Issue by Tuplanolla** [TIM-JYU/TIM#3724]
Tässä tapahtuu jotain, mitä järjellä ei voi selittää.
Jos määrittelen asiakirjan asetuksissa makron `numbers` siten, että

``` yaml
macros:
  numbers:
    three: |4*4
    one: 1
    two: 2
    *4
    five: 5
```

niin asiakirjan sisällä merkkijono `%% numbers %%`
laajentuu merkkijonoksi `{'one': 1, 'two': 2, 'three': '', 'five': 5}`.
Jos taas muutan makron `number` määritelmässä
yhdenkään rivin sisennystä tai sisältöä,
niin siitä seuraa lähes poikkeuksetta jäsennysvirhe.
