### ISSUE TITLE
QuantumSimulator: individual gate colors

### ISSUE THREAD

**Issue by saviit** [TIM-JYU/TIM#3848]
Currently, the quantum simulator plugin doesn't support changing the colors of the gates in the default gate set (X, H, Y, Z, etc.) via the plugin's markup. It can be done via CSS, but not without compromises.

Some users would like to customize the gate colors for the default set, so we should add a new attribute to handle that case:

```
gateColors:
  -
    name: "X"
    fillColor: "#FF0000"
    strokeColor: "#00FF00"
    textColor: "#000"
  -
    name: "Z"
    fillColor: "00FF00"
    strokeColor: "black"
    textColor: "#000"
```
