### ISSUE TITLE
Kuvien, taulukoiden yms. numerointi

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#411]
In GitLab by @Smibu on Nov 21, 2016, 13:33

Oletusnumerointityyli voisi olla:

ks myös #1201

X.Y missä X on luvun numero ja Y on elementtityypin (kuva/taulukko/listaus) juokseva numero luvussa.

Viittaaminen voi olla haastavampaa; siinä täytyy joka tapauksessa käydä doku ainakin osittain 2 kertaa läpi - ensimmäisessä vaiheessa katsotaan viittauskohdat ja lasketaan kuvien yms. numerointi ja toisessa vaiheessa laitetaan viittauskohtiin oikeat numerot (ja varmaankin kappale-id riittää linkiksi).

Periaatteessa pitäisi pystyä määrittelemään jonkinlaisia laskureita ja milloin ne nollautuvat. Jotenkin tyyliin

```
counters:
 lause:
  start: 1
  prepend: "Lause "
  reset_at: h1 // voisi olla myös "never"
​ esimerkki:
  start: 1
  prepend: "Esimerkki "
  reset_at: h1
```

​ja sitten md:ssä voisi käyttää noita kuten makroja (`## %%lause%%`).

TODO: Miten viittaaminen?

## Checklist

* [ ] Numerointi
* [ ] Numerointityylin säätö dokun asetuksella
* [ ] Numerointiin viittaaminen
