### ISSUE TITLE
Rekursiiviset ryhmät

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#513]
In GitLab by @Smibu on Mar 12, 2016, 10:01

Ryhmien "rekursio" niin, että ryhmään voi kuulu ryhmiä.

Jotta vältetään Korpin ryhmän aukilaskemisen ongelmat, pidetään
ryhmä aina aukilaskettuna.  Kun johonkin ryhmään lisätään/poistetaan
käydään katsomassa, missä kaikissa ryhmissä viitataan tähän
ryhmään ja lasketaan sen ryhmän jäsenet uudelleen.

Eli joka ryhmässä on aukilasketut yhden ihmisen ryhmät ja
lista laskettavista ryhmistä.   Pikkuisen tilaa voi säästään niin,
että ryhmässä on tieto siitä, onko siinä viitattuja ryhmiä ja
jos ei ole, niin yhden ihmisen ryhmiä ei ole 2x.

Eli tyyliin (* on ryhmä)

```
 ohj2opiskelijat:
  syötetyt:
    - kalle
    - ville
  aukilaskettu:

 ohj2opettajat
  syötetyt:
    - vesal
    - mikkihiiri
  aukilaskettu:

ohj2kurssi:
  syötetyt:
   - matti
   - ohj2opiskelijat*
   - ohj2opettajat*
  aukilaskettu:
  - matti
  - kalle
  - ville
  - vesal
  - mikkihiiri
```

ryhmään kuuluminen katsotaan noista aukilasketuista, paitsi jos se
on tyhjä, jolloin syötetyistä.  Näin ei-rukursiiviset ryhmät eivät
kasva, mutta rekursiisivissa on helposti jäsenet monta kertaa.

Ks alla oleva kommentti, eli nuo koosteryhmät voisivat olla vain erillinen "käyttöliittymä"
ylläpitää aukilaskettuja ryhmiä jolloin olemassa olevaan koodiin ei tarvittaisi isoja
muutoksia.

*Vesa Lappalainen*
