### ISSUE TITLE
Pelillistäminen käyttämään pistelaskun ryhmittelyä

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#579]
In GitLab by @Smibu on Aug 27, 2017, 13:49

Joissakin isoissa dokumenteissa dokumentin pelkistäminen yhteen linnaan
on aika tylsää.  Voisi olla mahdollisuus luetella sama dokumenti useita kertoja,
mutta sanoa erikseen etttä mikä ryhmä vastaa mitäkin linnaa.

Eli nykyiseen sellainen muutos, että dokumentin lisäksi sanotaan pistelaskun ryhmä.

Eli

```
demos:
    - path: "dokumentin_polku/isodoku"
      max_points: 6
      group: t1
    - path: "dokumentin_polku/isodoku"
      max_points: 10
      group: t2
    - path: "dokumentin_polku/isodoku"
      max_points: 12
      group: t3
```

*Vesa Lappalainen*
